# Generated by Django 4.2.5 on 2023-09-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_group_time_create_group_time_update_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='years',
            new_name='year_finish',
        ),
        migrations.AddField(
            model_name='album',
            name='year_start',
            field=models.SmallIntegerField(default=1990),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(upload_to='albums/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(upload_to='groups/'),
        ),
    ]
