# Generated by Django 4.2.5 on 2023-09-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_rename_years_album_year_finish_album_year_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='year_finish',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='album',
            name='year_start',
        ),
    ]
