# Generated by Django 4.2.5 on 2023-09-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_rename_year_finish_album_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='years',
            new_name='year',
        ),
    ]
