# Generated by Django 4.2.5 on 2023-09-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_rename_years_song_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default='w'),
            preserve_default=False,
        ),
    ]
