# Generated by Django 4.2.5 on 2023-09-28 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_character_group_character_song_character'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='character',
            new_name='char',
        ),
    ]
