# Generated by Django 4.1.7 on 2023-10-09 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_rename_character_character_char'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='language',
        ),
        migrations.RemoveField(
            model_name='song',
            name='year',
        ),
    ]
